/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Performance } from "./Performance";
import { PerformanceCountArgs } from "./PerformanceCountArgs";
import { PerformanceFindManyArgs } from "./PerformanceFindManyArgs";
import { PerformanceFindUniqueArgs } from "./PerformanceFindUniqueArgs";
import { DeletePerformanceArgs } from "./DeletePerformanceArgs";
import { PerformanceService } from "../performance.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Performance)
export class PerformanceResolverBase {
  constructor(
    protected readonly service: PerformanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "read",
    possession: "any",
  })
  async _performancesMeta(
    @graphql.Args() args: PerformanceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Performance])
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "read",
    possession: "any",
  })
  async performances(
    @graphql.Args() args: PerformanceFindManyArgs
  ): Promise<Performance[]> {
    return this.service.performances(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Performance, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "read",
    possession: "own",
  })
  async performance(
    @graphql.Args() args: PerformanceFindUniqueArgs
  ): Promise<Performance | null> {
    const result = await this.service.performance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Performance)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "delete",
    possession: "any",
  })
  async deletePerformance(
    @graphql.Args() args: DeletePerformanceArgs
  ): Promise<Performance | null> {
    try {
      return await this.service.deletePerformance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
