/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TransactionHistory } from "./TransactionHistory";
import { TransactionHistoryCountArgs } from "./TransactionHistoryCountArgs";
import { TransactionHistoryFindManyArgs } from "./TransactionHistoryFindManyArgs";
import { TransactionHistoryFindUniqueArgs } from "./TransactionHistoryFindUniqueArgs";
import { DeleteTransactionHistoryArgs } from "./DeleteTransactionHistoryArgs";
import { TransactionHistoryService } from "../transactionHistory.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TransactionHistory)
export class TransactionHistoryResolverBase {
  constructor(
    protected readonly service: TransactionHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TransactionHistory",
    action: "read",
    possession: "any",
  })
  async _transactionHistoriesMeta(
    @graphql.Args() args: TransactionHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TransactionHistory])
  @nestAccessControl.UseRoles({
    resource: "TransactionHistory",
    action: "read",
    possession: "any",
  })
  async transactionHistories(
    @graphql.Args() args: TransactionHistoryFindManyArgs
  ): Promise<TransactionHistory[]> {
    return this.service.transactionHistories(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TransactionHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TransactionHistory",
    action: "read",
    possession: "own",
  })
  async transactionHistory(
    @graphql.Args() args: TransactionHistoryFindUniqueArgs
  ): Promise<TransactionHistory | null> {
    const result = await this.service.transactionHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TransactionHistory)
  @nestAccessControl.UseRoles({
    resource: "TransactionHistory",
    action: "delete",
    possession: "any",
  })
  async deleteTransactionHistory(
    @graphql.Args() args: DeleteTransactionHistoryArgs
  ): Promise<TransactionHistory | null> {
    try {
      return await this.service.deleteTransactionHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
